---
# 设置批量管理节点
- hosts: zabbixagent
  # 远程访问的用户
  remote_user: root
  # 变量
  vars:

    # 配置文件目录
    workdir: /root/test/
    master_ip: 8.9.37.161
    master_url: http://8.9.37.161/zabbix/
    login_user: Admin
    login_password: zabbix
    
    

  tasks:
    - name: install zabbix-repo
      command: rpm -i http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm  creates=/etc/yum.repos.d/zabbix.repo warn=False

    - name: Install zabbix_sender
      yum: pkg=zabbix-sender state=installed
      
    - name: Install zabbix_get
      yum: pkg=zabbix-get state=installed
    
    - name: Install zabbix-agent
      yum: pkg=zabbix-agent state=installed
      
      # 启动zabbix-agent
    - name: start zabbix-agent
      service: name={{item.name}} state=started enabled=yes
      with_items:
      - { name: "zabbix-agent"}
    
      # 修改一些参数,如果需要修改一些其他参数,请根据自己的需求更改
    - name: change dbhost
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{item.regexp}}"
        line: "{{item.line}}"
      with_items:
      - { regexp: '^Server=' , line: 'Server={{master_ip}}' }
      - { regexp: '^ServerActive=' , line: 'ServerActive={{master_ip}}' }
      - { regexp: '^Hostname=' , line: 'Hostname={{inventory_hostname}}' }
      notify:
        - restart zabbix-agent

    - include: base_task/zabbix.yml
    
  handlers:
    - include: handlers/handlers.yml