---
# 设置批量管理节点
- hosts: node
  # 远程访问的用户
  remote_user: root
  # 变量
  vars:

    # 配置文件目录
    repodir: /etc/yum.repos.d/
    workdir: /var/tmps/

  tasks:
    - name: Create local directory to work from
      file: path={{workdir}} state=directory owner=root group=root mode=0751

    - name: clone nginx repo
      get_url: url=https://raw.githubusercontent.com/hewenyu/ansible_tmp/master/nginx-php/nginx.repo  dest={{repodir}}

      # 安装nginx
    - name: install nginx
      yum: pkg=nginx state=installed
      
      # 启动nginx
    - name: start nginx
      service: name=nginx state=started enabled=yes
    
    
    - name: Install epel-release
      yum: pkg=epel-release state=installed

    - name: install php repo
      command: rpm -i http://rpms.famillecollet.com/enterprise/remi-release-7.rpm  creates={{repodir}}remi.repo warn=False

    - name: install yum-utils
      yum: pkg=yum-utils state=installed
      
    - name: change php version
      shell: yum-config-manager --enable remi-php72 >> set.log  chdir={{workdir}} creates={{workdir}}set.log
      
    - name: install php_version
      yum: name={{item}} state=installed
      with_items:
        - php
        - php-fpm 
        - php-mysql 
        - php-bcmath 
        - php-gd
        - php-cli
        - php-common
        - php-mbstring 
        - php-pdo 
        - php-pear 
        - php-pecl-msgpack 
        - php-process 
        - php-xml 
        - gd-last 
        - php-json 
        - php-pecl-memcached 
        - php-pecl-zip

        
      # 启动php-fpm
    - name: start php-fpm
      service: name=php-fpm state=started enabled=yes

      # 修改php-fpm参数
    - name: change php-fpm
      ini_file:
        path: /etc/php-fpm.d/www.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { section: "www", option: "user", value: 'nginx' }
        - { section: "www", option: "group", value: 'nginx' }
        - { section: "www", option: "listen", value: '/var/run/php-fpm/php-fpm.sock' }
        - { section: "www", option: "listen.owner", value: 'nginx' }
        - { section: "www", option: "listen.group", value: 'nginx' }
        - { section: "www", option: "listen.mode", value: '0660' }
        - { section: "www", option: "access.log", value: '/var/log/php-fpm/$pool.access.log' }
        - { section: "www", option: "access.format", value: '"%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"' }
        - { section: "www", option: "slowlog", value: '/var/log/php-fpm/www-slow.log' }
        - { section: "www", option: "request_slowlog_timeout", value: '3' }
        - { section: "www", option: "php_value[session.save_handler]", value: 'files' }
        - { section: "www", option: "php_value[session.save_path]", value: '/var/lib/php/session' }
        - { section: "www", option: "php_value[session.wsdl_cache_dir]", value: '/var/lib/php/wsdlcache' }  
      notify:
        - restart php-fpm

    - name: mkdir session
      file: path=/var/lib/php/session state=directory owner=nginx group=nginx mode=0751
      
    - name: mkdir wsdlcache
      file: path=/var/lib/php/wsdlcache state=directory owner=nginx group=nginx mode=0751

    - name: clear_def
      shell: rm -rf  /etc/nginx/conf.d/default.conf >> default.log  chdir={{workdir}} creates={{workdir}}default.log

    
    - name: clear_nginx
      shell: rm -rf  /etc/nginx/nginx.conf >> nginx.log  chdir={{workdir}} creates={{workdir}}nginx.log
     
     # 修改nginx参数
    - name: copy config
      get_url: url={{item.url}} dest={{item.dest}} owner={{item.owner}}  group={{item.group}}  mode=0644
      with_items:
      - { url: "https://raw.githubusercontent.com/hewenyu/ansible_tmp/master/nginx-php/nginx.conf", dest: "/etc/nginx/nginx.conf", owner: "root", group : "root"}
      - { url: "https://raw.githubusercontent.com/hewenyu/ansible_tmp/master/nginx-php/enable-php.conf", dest: "/etc/nginx/enable-php.conf", owner: "root", group : "root"}
      - { url: "https://raw.githubusercontent.com/hewenyu/ansible_tmp/master/nginx-php/default.conf", dest: "/etc/nginx/conf.d/default.conf", owner: "root", group : "root"}
      - { url: "https://raw.githubusercontent.com/hewenyu/ansible_tmp/master/nginx-php/info.php", dest: "/usr/share/nginx/html/info.php", owner: "nginx", group : "nginx"}
      notify:
        - restart nginx
    
      
  handlers:
    - name: restart nginx
      service:  name=nginx state=restarted
    - name: restart php-fpm
      service: name=php-fpm state=restarted